# Generated by Django 5.0.1 on 2024-01-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='title',
            field=models.CharField(default='Your Default Value', max_length=255),
        ),
    ]
